sudo: required

services:
  - docker
  
language: python
python:
  - "3.6"

#BACKBONE_ID must be a trusted public network
env:
  global:
    - INVENTORY_DRIVER=local
    - 
    
before_install:
  - sudo docker pull ansible/ansible-runner
  - |
    bash -c "curl -s 'https://raw.githubusercontent.com/zerotier/download.zerotier.com/master/htdocs/contact%40zerotier.com.gpg'|gpg --import && \
             if z=$(curl -s 'https://install.zerotier.com/' | gpg); then echo "$z" | sudo bash && sudo zerotier-cli join ${BACKBONE_ID}; fi"

install:
  - pip install -r requirements.txt
  - ansible-galaxy install -r requirements.yml
  
script:
  - sudo zerotier-cli listpeers
  - ansible-playbook site.yml

notifications:
  email:
    - support@dapla.net
